# (C) 2001-2025 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# TCL File Generated by Component Editor 14.1
# Fri May 09 18:08:10 MYT 2014
# DO NOT MODIFY


# 
# altera_epcq_controller_core "Altera EPCQ Serial Flash controller core" v14.1
# Altera Coorperation 2014.05.23.15:01:29
# This component is a serial flash controller which allows user to access Altera EPCQ devices
# 

# 
# request TCL package from ACDS 14.1
# 
package require -exact qsys 14.1



# 
# module altera_epcq_controller
# 
set_module_property NAME intel_generic_serial_flash_interface_addr_swapped
set_module_property VERSION 24.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Intel Corporation"
set_module_property DISPLAY_NAME "Intel Generic QSPI Addr Adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_QUARTUS true
set_module_property EDITABLE true
set_module_property GROUP     "Basic Functions/Configuration and Programming"
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
# 
# file sets
# 

add_fileset synthesis_fileset QUARTUS_SYNTH synth_callback_procedure
set_fileset_property synthesis_fileset TOP_LEVEL intel_generic_serial_flash_interface_addr_swapped 
add_fileset simulation_fileset SIM_VERILOG synth_callback_procedure
set_fileset_property simulation_fileset TOP_LEVEL intel_generic_serial_flash_interface_addr_swapped
add_fileset vhdl_fileset SIM_VHDL synth_callback_procedure
set_fileset_property vhdl_fileset TOP_LEVEL intel_generic_serial_flash_interface_addr_swapped

proc synth_callback_procedure { entity_name } {
    add_fileset_file intel_generic_serial_flash_interface_addr_swapped.sv SYSTEM_VERILOG PATH "intel_generic_serial_flash_interface_addr_swapped.sv"
}



#
# add system info parameter
add_parameter           deviceFeaturesSystemInfo   STRING 			"None"
set_parameter_property  deviceFeaturesSystemInfo   system_info		"DEVICE_FEATURES"
set_parameter_property  deviceFeaturesSystemInfo   VISIBLE true

# 
# parameters
# 


add_parameter           DEVICE_FAMILY		STRING          ""
set_parameter_property  DEVICE_FAMILY		SYSTEM_INFO     "DEVICE_FAMILY"
set_parameter_property  DEVICE_FAMILY		HDL_PARAMETER   false
set_parameter_property  DEVICE_FAMILY		VISIBLE	      	false

add_parameter ADDR_WIDTH INTEGER 19
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 19
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH DERIVED false
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH VISIBLE true
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES {15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28}
set_parameter_property ADDR_WIDTH HDL_PARAMETER true


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

# 
# connection point avl_mem
# 
add_interface avl_mem avalon end
set_interface_property avl_mem addressUnits WORDS
set_interface_property avl_mem associatedClock clock_sink
set_interface_property avl_mem associatedReset reset
set_interface_property avl_mem bitsPerSymbol 8
set_interface_property avl_mem burstOnBurstBoundariesOnly false
set_interface_property avl_mem burstcountUnits WORDS
set_interface_property avl_mem explicitAddressSpan 0
set_interface_property avl_mem holdTime 0
set_interface_property avl_mem linewrapBursts true
set_interface_property avl_mem maximumPendingReadTransactions 1
set_interface_property avl_mem maximumPendingWriteTransactions 0
set_interface_property avl_mem constantBurstBehavior true
set_interface_property avl_mem readLatency 0
set_interface_property avl_mem readWaitTime 0
set_interface_property avl_mem setupTime 0
set_interface_property avl_mem timingUnits Cycles
set_interface_property avl_mem writeWaitTime 0
set_interface_property avl_mem ENABLED true
set_interface_property avl_mem EXPORT_OF ""
set_interface_property avl_mem PORT_NAME_MAP ""
set_interface_property avl_mem CMSIS_SVD_VARIABLES ""
set_interface_property avl_mem SVD_ADDRESS_GROUP ""

# interface assignments for embedded software
set_interface_assignment avl_mem embeddedsw.configuration.isFlash 1
set_interface_assignment avl_mem embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avl_mem embeddedsw.configuration.isNonVolatileStorage 1
set_interface_assignment avl_mem embeddedsw.configuration.isPrintableDevice 0

add_interface_port avl_mem avl_mem_write write Input 1
add_interface_port avl_mem avl_mem_burstcount burstcount Input 7
add_interface_port avl_mem avl_mem_waitrequest waitrequest Output 1
add_interface_port avl_mem avl_mem_read read Input 1
add_interface_port avl_mem avl_mem_addr address Input ADDR_WIDTH
add_interface_port avl_mem avl_mem_wrdata writedata Input 32
add_interface_port avl_mem avl_mem_rddata readdata Output 32
add_interface_port avl_mem avl_mem_rddata_valid readdatavalid Output 1
add_interface_port avl_mem avl_mem_byteenable byteenable Input 4

# 
# connection point mem
# 
add_interface gen_qspi_mem avalon start
set_interface_property gen_qspi_mem addressUnits WORDS
set_interface_property gen_qspi_mem associatedClock clock_sink
set_interface_property gen_qspi_mem associatedReset reset
set_interface_property gen_qspi_mem bitsPerSymbol 8
set_interface_property gen_qspi_mem burstOnBurstBoundariesOnly false
set_interface_property gen_qspi_mem burstcountUnits WORDS
set_interface_property gen_qspi_mem holdTime 0
set_interface_property gen_qspi_mem linewrapBursts false
set_interface_property gen_qspi_mem maximumPendingReadTransactions 1
set_interface_property gen_qspi_mem maximumPendingWriteTransactions 0
set_interface_property gen_qspi_mem readLatency 0
set_interface_property gen_qspi_mem readWaitTime 1
set_interface_property gen_qspi_mem setupTime 0
set_interface_property gen_qspi_mem timingUnits Cycles
set_interface_property gen_qspi_mem writeWaitTime 0
set_interface_property gen_qspi_mem ENABLED true
set_interface_property gen_qspi_mem EXPORT_OF ""
set_interface_property gen_qspi_mem PORT_NAME_MAP ""
set_interface_property gen_qspi_mem CMSIS_SVD_VARIABLES ""
set_interface_property gen_qspi_mem SVD_ADDRESS_GROUP ""

add_interface_port gen_qspi_mem gen_qspi_mem_addr address Output 32
add_interface_port gen_qspi_mem gen_qspi_mem_read read Output 1
add_interface_port gen_qspi_mem gen_qspi_mem_rddata readdata Input 32
add_interface_port gen_qspi_mem gen_qspi_mem_write write Output 1
add_interface_port gen_qspi_mem gen_qspi_mem_wrdata writedata Output 32
add_interface_port gen_qspi_mem gen_qspi_mem_byteenable byteenable Output 4
add_interface_port gen_qspi_mem gen_qspi_mem_burstcount burstcount Output 7
add_interface_port gen_qspi_mem gen_qspi_mem_waitrequest waitrequest Input 1
add_interface_port gen_qspi_mem gen_qspi_mem_rddata_valid readdatavalid Input 1


proc proc_get_derive_addr_width {flash_type} {
    switch $flash_type {
        "EPCQ16" - "N25Q16" {
            return 19 
        }
		"EPCQ32" - "N25Q32" {
            return 20
		}
        "EPCQ64" - "N25Q64" {
            return 21
        }
        "EPCQ128" - "N25Q128" {
            return 22
        }
        "EPCQ256" - "EPCQL256" - "N25Q256" - "N25Q256-L" - "EPCQL256A" - "MT25QL256" - "MT25QU256" {
            return 23
        }
        "EPCQ512" - "EPCQL512" - "EPCQL512A" - "N25Q512" - "N25Q512-L" - "Micron512" - "MT25QL512" - "MT25QU512" {
            return 24
        }
        "EPCQL1024" - "EPCQL1024A" - "N25Q1024-L" - "MT25QU01G" {
            return 25
        }
        default {
            # Should never enter this function
            send_message error "$flash_type is not a valid flash type"
        }
    }
}
